### PR TITLE
support more configs for processor and connection

### PR DESCRIPTION
**Pull request by raymond-ti**
Changes:
- support executionNode for processor
- support backPressureDataSizeThreshold and backPressureObjectThreshold for connection

### CODE REVIEW

**Comment by egorpushkin** [comment]
@raymond-ti Nice additions! Could you please confirm that all changes were gofmt'ed.

**Comment by raymond-ti** [comment]
I used Sublime Text with GoSublime package to edit the code, I think it should be gofmt'ed.

**Comment by analytically** [comment]
+1

**Comment by egorpushkin** [comment]
LGTM
@raymond-ti Nicely done!

**Pull request merged**
