### PR TITLE
Add reporting task

### PR DESCRIPTION
**Pull request by KailasJanardhanan**

### CODE REVIEW

**Comment by KailasJanardhanan** [comment]
Adding changes to support Reporting tasks

**Comment by shashanksurya** [comment]
@egorpushkin Please review our enhancement for reporting tasks. Thanks :)

**Comment by egorpushkin** [comment]
@KailasJanardhanan @shashanksurya Could you please 
- add unit test for newly added NiFi  client functionality;
- confirm that gofmt has been run against the changes.

**Comment by KailasJanardhanan** [comment]
added testcase for reporting tasks and ran gofmt against the modified files

**Comment by egorpushkin** [comment]
LGTM

**Pull request merged**
